# Generated by Django 3.0.6 on 2020-05-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_2', '0002_auto_20200516_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shit',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
